name: Main
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: test before
      shell: bash
      run: rustup --version || echo "not installed"
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      #with:
      #  rust-version: ${{ matrix.rust }}
    - name: test after
      shell: bash
      run: rustup --version